apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-child-3
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  project: default
  source:
    path: .
    repoURL: https://github.com/alina-codefresh/rollouts-demo.git
    targetRevision: onprem-testing
  destination:
    name: in-cluster
    namespace: test-onprem
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=false
      - ServerSideApply=true
      - RespectIgnoreDifferences=false
